name: Publish-DTS

on:
  workflow_dispatch:


jobs:
  publish:
    name: "Publish to npm registry"
    runs-on: ubuntu-latest
    steps:
      
      - uses: actions/checkout@v4
      - uses: actions/setup-node@v4
        with:
          node-version: '22.17.0'
          registry-url: 'https://registry.npmjs.org'

      - uses: ./.github/actions/setup-env

      - run: npm run generate:dts

      - run: cp packages/engine/bin/.declarations/cc.d.ts packages/cocos-cli-types/cc.d.ts

      - run: npx eslint --fix "./packages/cocos-cli-types/*.d.ts"

      - run: npx jest packages/cocos-cli-types --roots="<rootDir>/packages/cocos-cli-types"

      - name: Remove local .npmrc to avoid registry conflict
        run: rm -f .npmrc

      - name: Publish to npm
        run: npm publish --access public
        working-directory: packages/cocos-cli-types
        env:
          NODE_AUTH_TOKEN: ${{ secrets.NPM_PUBLISH }}
